# Fuel Economy EDA with sqlframe library

In [1]:
from sqlframe.base.dataframe import BaseDataFrame
from sqlframe.duckdb import DuckDBSession
from sqlframe.duckdb.types import StructType, StructField, StringType, IntegerType
from sqlframe.duckdb import Window
import sqlframe.duckdb.functions as F

# For "prettier" printing of data frame tables in jupyterlab notebook, will convert to polars data frame
import polars as pl
pl.Config.set_tbl_rows(100)
pl.Config.set_tbl_cols(50)

# sqlframe doesn't support a .toPolars() conversion method, so will "monkey patch" one here:
def _to_polars(self) -> pl.DataFrame:
    return pl.from_arrow(self.toArrow())

BaseDataFrame.toPolars = _to_polars

In [3]:
session = DuckDBSession()

In [ ]:
# data dictionary can be found at: https://www.fueleconomy.gov/feg/ws/index.shtml#vehicle
df = session.read.csv("https://www.fueleconomy.gov/feg/epadata/vehicles.csv", inferSchema=False)

In [ ]:
df.printSchema()

#### There are too many columns, so I'll limit to just the ones that I'm interested in:

In [ ]:
df_final = (
    df.select(
        F.col("year"),
        F.col("make"),
        F.col("model"),
        F.col("basemodel"),
        F.col("trany").alias("transmission_type"),
        F.col("atvType").alias("alt_fuel_adv_tech_veh_type"),
        F.col("fuelType"),
        F.col("fuelType1"),
        F.col("fuelType2"),
        F.col("charge120").alias("hours_to_fully_charge_120v"),
        F.col("charge240").alias("hours_to_fully_charge_240v"),
        F.col("city08").alias("city_mpg_fuel_type1"),
        F.col("cityA08").alias("city_mpg_fuel_type2"),
        F.col("highway08").alias("hwy_mpg_fuel_type1"),
        F.col("highwayA08").alias("hwy_mpg_fuel_type2"),
        F.col("comb08").alias("comb_mpg_fuel_type1"),
        F.col("combA08").alias("comb_mpg_fuel_type2"),
        F.col("phevCity"),
        F.col("phevHwy"),
        F.col("phevComb"),
    )
)

In [ ]:
df_final.toPolars().head()

## Let's see what distinct values are in the alternate fuel/advance technology vehicle type column:

In [ ]:
(
    df_final
    .select(
        F.col("alt_fuel_adv_tech_veh_type")
    )
    .distinct()
).show()

#### On average, how long does it take for a 2026 model electric vehicle to fully charge using 240 volt charger?

In [ ]:
(
    df_final
    .filter(
        (F.col("fuelType1").like("%Elec%")) &
        (F.col("year") == 2026)
    )
    .agg(
        F.avg(
            F.col("hours_to_fully_charge_240v")
        ).alias("Avg Hours to Fully Charge 240V")
    )
).show()

#### What is the longest time to charge a 2026 EV vehicle with a 240 volt charger?

In [ ]:
(
    df_final
    .filter(
        (F.col("fuelType1").like("%Elec%"))
        & (F.col("year") == 2026)
    )
    .agg(
        F.max(
            F.col("hours_to_fully_charge_240v")
        ).alias("Max Hours to Fully Charge 240V")
    )
).show()

#### What is the shortest time to charge a 2026 EV vehicle with a 240 volt charger?

In [ ]:
(
    df_final
    .filter(
        (F.col("fuelType1").like("%Elec%"))
        & (F.col("year") == 2026)
    )
    .agg(
        F.min(
            F.col("hours_to_fully_charge_240v")
        ).alias("Min Hours to Fully Charge 240V")
    )
).show()

#### What if I want to know the year, make, and models associated with the longest and shortest charge times?  One way is to use a `Window.partitionBy()`.

Fastest charging models:

In [ ]:
w = Window.partitionBy()  # whole dataset

(
    df_final
    .filter(
        (F.col("fuelType1").like("%Elec%"))
        & (F.col("year") == 2026)
    )
    .withColumn("min_hours", F.min("hours_to_fully_charge_240v").over(w))
    .filter(F.col("hours_to_fully_charge_240v") == F.col("min_hours"))
    .select(
        "year",
        "make",
        "model",
        "fuelType1",
        "fuelType2",
        F.col("hours_to_fully_charge_240v").alias("Min Hours to Fully Charge 240V")
    )
).show()

Slowest charging models:

In [ ]:
w = Window.partitionBy()  # whole dataset

(
    df_final
    .filter(
        (F.col("fuelType1").like("%Elec%"))
        & (F.col("year") == 2026)
    )
    .withColumn("max_hours", F.max("hours_to_fully_charge_240v").over(w))
    .filter(F.col("hours_to_fully_charge_240v") == F.col("max_hours"))
    .select(
        "year",
        "make",
        "model",
        F.col("hours_to_fully_charge_240v").alias("Max Hours to Fully Charge 240V")
    )
).show()

#### With ICE, gasoline vehicles, one would think with each passing model year, the combined MPG should be highest compared to all other previous model years.  But let's confirm by obtaining the average combined MPG for all ICE, gasoline-exclusive vehicles by model year:

In [ ]:
# +----------------------------+
# | alt_fuel_adv_tech_veh_type |
# +----------------------------+
# |            None            |
# |             EV             |
# |           Hybrid           |
# |       Plug-in Hybrid       |
# |            FFV             |
# |           Diesel           |
# |            FCV             |
# |            eFCV            |
# |            CNG             |
# |        Bifuel (CNG)        |
# |        Bifuel (LPG)        |
# +----------------------------+


(
    df_final
    .filter(
        F.col("fuelType1").like("%Gasoline%")
        & (F.col("fuelType2").isNull() | (F.col("fuelType2") == ""))
        & (
            F.col("alt_fuel_adv_tech_veh_type").isNull()
            | ~F.col("alt_fuel_adv_tech_veh_type").isin("EV", "Hybrid", "Plug-in Hybrid", "FFV", "Diesel","FCV","eFCV","CNG","Bifuel (CNG)","Bifuel (LPG)")
        )
    )
    .groupBy("year")
    .agg(F.avg("comb_mpg_fuel_type1").alias("avg_comb_mpg_fuel_type1"))
    .orderBy(F.col("year"))
).toPolars()

From above we see that recent model years' MPG aren't the highest.

Based on visually looking at the table above, we see that 2018 had highest average combined MPG.  But how do we determine the model year with highest average combined MPG using sqlframe or without having to visually look at the data?

**Using groupBy, then agg():**

In [ ]:
(
    df_final
    .filter(
        F.col("fuelType1").like("%Gasoline%")
        & (F.col("fuelType2").isNull() | (F.col("fuelType2") == ""))
        & (
            F.col("alt_fuel_adv_tech_veh_type").isNull()
            | ~F.col("alt_fuel_adv_tech_veh_type").isin("EV", "Hybrid", "Plug-in Hybrid", "FFV", "Diesel","FCV","eFCV","CNG","Bifuel (CNG)","Bifuel (LPG)")
        )
    )
    .groupBy("year")
    .agg(F.avg("comb_mpg_fuel_type1").alias("avg_comb_mpg_fuel_type1"))
    .orderBy(F.col("avg_comb_mpg_fuel_type1").desc())
    .limit(1)
).toPolars()

**Obtain average, combined MPG, but also add a new column containing the actual max average combined MPG using max(), then Window.partitionBy():**

In [ ]:
(
    df_final
    .filter(
        F.col("fuelType1").like("%Gasoline%")
        & (F.col("fuelType2").isNull() | (F.col("fuelType2") == ""))
        & (
            F.col("alt_fuel_adv_tech_veh_type").isNull()
            | ~F.col("alt_fuel_adv_tech_veh_type").isin("EV", "Hybrid", "Plug-in Hybrid", "FFV", "Diesel","FCV","eFCV","CNG","Bifuel (CNG)","Bifuel (LPG)")
        )
    )
    .groupBy("year")
    .agg(F.avg("comb_mpg_fuel_type1").alias("avg_comb_mpg_fuel_type1"))
    .withColumn(
        "max_avg_comb_mpg_fuel_type1",
        F.max("avg_comb_mpg_fuel_type1").over(Window.partitionBy())
    )
    .filter(F.col("avg_comb_mpg_fuel_type1") == F.col("max_avg_comb_mpg_fuel_type1"))
).toPolars()

## Let's obtain the top 3 vehicle makes with highest combined MPG from 2016 through 2026 model years

Create a new `rank` column which is rank within each model year.  The `within each year` is a signal or clue to us that `year` is the `partition` that we want our rank to delineate or separate on.  In most business contexts, `dense rank` is what we should be using since we want ties to have the same rank, not different rank.

In [ ]:
w = Window.partitionBy("year").orderBy(F.col("max_comb_mpg").desc())

(
    df_final
    .filter(
        F.col("fuelType1").like("%Gasoline%")
        & (
            F.col("alt_fuel_adv_tech_veh_type").isNull()
            | ~F.col("alt_fuel_adv_tech_veh_type").isin("EV", "Hybrid", "Plug-in Hybrid", "FFV", "Diesel","FCV","eFCV","CNG","Bifuel (CNG)","Bifuel (LPG)")
        )
        & (
            F.col("year").between(2016,2026)
        )
    )
    .groupBy(
        "year","make"
    )
    .agg(
        F.max(F.col("comb_mpg_fuel_type1")).alias("max_comb_mpg")
    )
    .withColumn(
        "rank", F.dense_rank().over(w)
    )
    .orderBy(
        F.col("year"),
        F.col("rank")
    )
    # Comment out .filter to see the unfiltered version
    .filter(
        F.col("rank").between(1,3)
    )
).toPolars()

In [4]:
df_cars = session.read.csv("https://jacobceles.github.io/knowledge_repo/colab_and_pyspark/cars.csv", header=True, sep=";")

In [5]:
df_cars.toPolars().tail()

shape: (5, 9)
┌───────────────────┬──────┬───────────┬──────────────┬────────────┬────────┬──────────────┬───────┬────────┐
│ Car               ┆ MPG  ┆ Cylinders ┆ Displacement ┆ Horsepower ┆ Weight ┆ Acceleration ┆ Model ┆ Origin │
│ ---               ┆ ---  ┆ ---       ┆ ---          ┆ ---        ┆ ---    ┆ ---          ┆ ---   ┆ ---    │
│ str               ┆ f64  ┆ i64       ┆ f64          ┆ f64        ┆ f64    ┆ f64          ┆ i64   ┆ str    │
╞═══════════════════╪══════╪═══════════╪══════════════╪════════════╪════════╪══════════════╪═══════╪════════╡
│ Ford Mustang GL   ┆ 27.0 ┆ 4         ┆ 140.0        ┆ 86.0       ┆ 2790.0 ┆ 15.6         ┆ 82    ┆ US     │
│ Volkswagen Pickup ┆ 44.0 ┆ 4         ┆ 97.0         ┆ 52.0       ┆ 2130.0 ┆ 24.6         ┆ 82    ┆ Europe │
│ Dodge Rampage     ┆ 32.0 ┆ 4         ┆ 135.0        ┆ 84.0       ┆ 2295.0 ┆ 11.6         ┆ 82    ┆ US     │
│ Ford Ranger       ┆ 28.0 ┆ 4         ┆ 120.0        ┆ 79.0       ┆ 2625.0 ┆ 18.6         ┆ 82    ┆ US     │
│ Chevy S-10        ┆ 31.0 ┆ 4         ┆ 119.0        ┆ 82.0       ┆ 2720.0 ┆ 19.4         ┆ 82    ┆ US     │
└───────────────────┴──────┴───────────┴──────────────┴────────────┴────────┴──────────────┴───────┴────────┘

## Running Total Example

In [10]:
w = (
    Window
    .partitionBy(F.col("Origin"))
    .orderBy(F.col("Model"), F.col("Car"))  # defines "running" order
    .rowsBetween(Window.unboundedPreceding, Window.currentRow)
)

(
    df_cars
    .withColumn("cumulative_sum_on_mpg", F.sum(F.col("MPG")).over(w))
).toPolars()

shape: (406, 10)
┌─────────────────────────────────┬──────┬───────────┬──────────────┬────────────┬────────┬──────────────┬───────┬────────┬───────────────────────┐
│ Car                             ┆ MPG  ┆ Cylinders ┆ Displacement ┆ Horsepower ┆ Weight ┆ Acceleration ┆ Model ┆ Origin ┆ cumulative_sum_on_mpg │
│ ---                             ┆ ---  ┆ ---       ┆ ---          ┆ ---        ┆ ---    ┆ ---          ┆ ---   ┆ ---    ┆ ---                   │
│ str                             ┆ f64  ┆ i64       ┆ f64          ┆ f64        ┆ f64    ┆ f64          ┆ i64   ┆ str    ┆ f64                   │
╞═════════════════════════════════╪══════╪═══════════╪══════════════╪════════════╪════════╪══════════════╪═══════╪════════╪═══════════════════════╡
│ Datsun PL510                    ┆ 27.0 ┆ 4         ┆ 97.0         ┆ 88.0       ┆ 2130.0 ┆ 14.5         ┆ 70    ┆ Japan  ┆ 27.0                  │
│ Toyota Corolla Mark ii          ┆ 24.0 ┆ 4         ┆ 113.0        ┆ 95.0       ┆ 2372.0 ┆ 15.0         ┆ 70    ┆ Japan  ┆ 51.0                  │
│ Datsun 1200                     ┆ 35.0 ┆ 4         ┆ 72.0         ┆ 69.0       ┆ 1613.0 ┆ 18.0         ┆ 71    ┆ Japan  ┆ 86.0                  │
│ Datsun PL510                    ┆ 27.0 ┆ 4         ┆ 97.0         ┆ 88.0       ┆ 2130.0 ┆ 14.5         ┆ 71    ┆ Japan  ┆ 113.0                 │
│ Toyota Corolla                  ┆ 25.0 ┆ 4         ┆ 113.0        ┆ 95.0       ┆ 2228.0 ┆ 14.0         ┆ 71    ┆ Japan  ┆ 138.0                 │
│ Toyota Corolla 1200             ┆ 31.0 ┆ 4         ┆ 71.0         ┆ 65.0       ┆ 1773.0 ┆ 19.0         ┆ 71    ┆ Japan  ┆ 169.0                 │
│ Datsun 510 (sw)                 ┆ 28.0 ┆ 4         ┆ 97.0         ┆ 92.0       ┆ 2288.0 ┆ 17.0         ┆ 72    ┆ Japan  ┆ 197.0                 │
│ Mazda RX2 Coupe                 ┆ 19.0 ┆ 3         ┆ 70.0         ┆ 97.0       ┆ 2330.0 ┆ 13.5         ┆ 72    ┆ Japan  ┆ 216.0                 │
│ Toyota Corolla 1600 (sw)        ┆ 27.0 ┆ 4         ┆ 97.0         ┆ 88.0       ┆ 2100.0 ┆ 16.5         ┆ 72    ┆ Japan  ┆ 243.0                 │
│ Toyota Corolla Hardtop          ┆ 24.0 ┆ 4         ┆ 113.0        ┆ 95.0       ┆ 2278.0 ┆ 15.5         ┆ 72    ┆ Japan  ┆ 267.0                 │
│ Toyota Corolla Mark II (sw)     ┆ 23.0 ┆ 4         ┆ 120.0        ┆ 97.0       ┆ 2506.0 ┆ 14.5         ┆ 72    ┆ Japan  ┆ 290.0                 │
│ Datsun 610                      ┆ 22.0 ┆ 4         ┆ 108.0        ┆ 94.0       ┆ 2379.0 ┆ 16.5         ┆ 73    ┆ Japan  ┆ 312.0                 │
│ Mazda RX3                       ┆ 18.0 ┆ 3         ┆ 70.0         ┆ 90.0       ┆ 2124.0 ┆ 13.5         ┆ 73    ┆ Japan  ┆ 330.0                 │
│ Toyota Camry                    ┆ 20.0 ┆ 4         ┆ 97.0         ┆ 88.0       ┆ 2279.0 ┆ 19.0         ┆ 73    ┆ Japan  ┆ 350.0                 │
│ Toyota Mark II                  ┆ 20.0 ┆ 6         ┆ 156.0        ┆ 122.0      ┆ 2807.0 ┆ 13.5         ┆ 73    ┆ Japan  ┆ 370.0                 │
│ Datsun 710                      ┆ 32.0 ┆ 4         ┆ 83.0         ┆ 61.0       ┆ 2003.0 ┆ 19.0         ┆ 74    ┆ Japan  ┆ 402.0                 │
│ Datsun B210                     ┆ 31.0 ┆ 4         ┆ 79.0         ┆ 67.0       ┆ 1950.0 ┆ 19.0         ┆ 74    ┆ Japan  ┆ 433.0                 │
│ Honda Civic                     ┆ 24.0 ┆ 4         ┆ 120.0        ┆ 97.0       ┆ 2489.0 ┆ 15.0         ┆ 74    ┆ Japan  ┆ 457.0                 │
│ Subaru                          ┆ 26.0 ┆ 4         ┆ 108.0        ┆ 93.0       ┆ 2391.0 ┆ 15.5         ┆ 74    ┆ Japan  ┆ 483.0                 │
│ Toyota Corolla                  ┆ 31.0 ┆ 4         ┆ 76.0         ┆ 52.0       ┆ 1649.0 ┆ 16.5         ┆ 74    ┆ Japan  ┆ 514.0                 │
│ Toyota Corolla 1200             ┆ 32.0 ┆ 4         ┆ 71.0         ┆ 65.0       ┆ 1836.0 ┆ 21.0         ┆ 74    ┆ Japan  ┆ 546.0                 │
│ Datsun 710                      ┆ 24.0 ┆ 4         ┆ 119.0        ┆ 97.0       ┆ 2545.0 ┆ 17.0         ┆ 75    ┆ Japan  ┆ 570.0                 │
│ Honda Civic CVCC                ┆ 33.0 ┆ 4         ┆ 91.0         ┆ 53.0       ┆ 1795.0 ┆ 17.5         ┆ 75    ┆ Japan  ┆ 603.0                 │
│ Toyota Corolla                  ┆ 29.0 ┆ 4         ┆ 97.0         ┆ 75.0       ┆ 2171.0 ┆ 16.0         ┆ 75    ┆ Japan  ┆ 632.0                 │
│ Toyota Corolla                  ┆ 24.0 ┆ 4         ┆ 134.0        ┆ 96.0       ┆ 2702.0 ┆ 13.5         ┆ 75    ┆ Japan  ┆ 656.0                 │
│ Datsun B-210                    ┆ 32.0 ┆ 4         ┆ 85.0         ┆ 70.0       ┆ 1990.0 ┆ 17.0         ┆ 76    ┆ Japan  ┆ 688.0                 │
│ Honda Civic                     ┆ 33.0 ┆ 4         ┆ 91.0         ┆ 53.0       ┆ 1795.0 ┆ 17.4         ┆ 76    ┆ Japan  ┆ 721.0                 │
│ Toyota Corolla                  ┆ 28.0 ┆ 4         ┆ 97.0         ┆ 75.0       ┆ 2155.0 ┆ 16.4         ┆ 76    ┆ Japan  ┆ 749.0                 │
│ Toyota Mark II                  ┆ 19.0 ┆ 6         ┆ 156.0        ┆ 108.0      ┆ 2930.0 ┆ 15.5         ┆ 76    ┆ Japan  ┆ 768.0                 │
│ Datsun 810                      ┆ 22.0 ┆ 6         ┆ 146.0        ┆ 97.0       ┆ 2815.0 ┆ 14.5         ┆ 77    ┆ Japan  ┆ 790.0                 │
│ Datsun F-10 Hatchback           ┆ 33.5 ┆ 4         ┆ 85.0         ┆ 70.0       ┆ 1945.0 ┆ 16.8         ┆ 77    ┆ Japan  ┆ 823.5                 │
│ Honda Accord CVCC               ┆ 31.5 ┆ 4         ┆ 98.0         ┆ 68.0       ┆ 2045.0 ┆ 18.5         ┆ 77    ┆ Japan  ┆ 855.0                 │
│ Mazda RX-4                      ┆ 21.5 ┆ 3         ┆ 80.0         ┆ 110.0      ┆ 2720.0 ┆ 13.5         ┆ 77    ┆ Japan  ┆ 876.5                 │
│ Subaru DL                       ┆ 30.0 ┆ 4         ┆ 97.0         ┆ 67.0       ┆ 1985.0 ┆ 16.4         ┆ 77    ┆ Japan  ┆ 906.5                 │
│ Toyota Corolla Liftback         ┆ 26.0 ┆ 4         ┆ 97.0         ┆ 75.0       ┆ 2265.0 ┆ 18.2         ┆ 77    ┆ Japan  ┆ 932.5                 │
│ Datsun 200-SX                   ┆ 23.9 ┆ 4         ┆ 119.0        ┆ 97.0       ┆ 2405.0 ┆ 14.9         ┆ 78    ┆ Japan  ┆ 956.4                 │
│ Datsun 510                      ┆ 27.2 ┆ 4         ┆ 119.0        ┆ 97.0       ┆ 2300.0 ┆ 14.7         ┆ 78    ┆ Japan  ┆ 983.6                 │
│ Datsun B210 GX                  ┆ 39.4 ┆ 4         ┆ 85.0         ┆ 70.0       ┆ 2070.0 ┆ 18.6         ┆ 78    ┆ Japan  ┆ 1023.0                │
│ Honda Accord LX                 ┆ 29.5 ┆ 4         ┆ 98.0         ┆ 68.0       ┆ 2135.0 ┆ 16.6         ┆ 78    ┆ Japan  ┆ 1052.5                │
│ Honda Civic CVCC                ┆ 36.1 ┆ 4         ┆ 91.0         ┆ 60.0       ┆ 1800.0 ┆ 16.4         ┆ 78    ┆ Japan  ┆ 1088.6                │
│ Mazda GLC Deluxe                ┆ 32.8 ┆ 4         ┆ 78.0         ┆ 52.0       ┆ 1985.0 ┆ 19.4         ┆ 78    ┆ Japan  ┆ 1121.4                │
│ Toyota Celica GT Liftback       ┆ 21.1 ┆ 4         ┆ 134.0        ┆ 95.0       ┆ 2515.0 ┆ 14.8         ┆ 78    ┆ Japan  ┆ 1142.5                │
│ Toyota Corolla                  ┆ 27.5 ┆ 4         ┆ 134.0        ┆ 95.0       ┆ 2560.0 ┆ 14.2         ┆ 78    ┆ Japan  ┆ 1170.0                │
│ Datsun 210                      ┆ 31.8 ┆ 4         ┆ 85.0         ┆ 65.0       ┆ 2020.0 ┆ 19.2         ┆ 79    ┆ Japan  ┆ 1201.8                │
│ Mazda GLC Deluxe                ┆ 34.1 ┆ 4         ┆ 86.0         ┆ 65.0       ┆ 1975.0 ┆ 15.2         ┆ 79    ┆ Japan  ┆ 1235.9                │
│ Datsun 210                      ┆ 40.8 ┆ 4         ┆ 85.0         ┆ 65.0       ┆ 2110.0 ┆ 19.2         ┆ 80    ┆ Japan  ┆ 1276.7                │
│ Datsun 280-ZX                   ┆ 32.7 ┆ 6         ┆ 168.0        ┆ 132.0      ┆ 2910.0 ┆ 11.4         ┆ 80    ┆ Japan  ┆ 1309.4                │
│ Datsun 310                      ┆ 37.2 ┆ 4         ┆ 86.0         ┆ 65.0       ┆ 2019.0 ┆ 16.4         ┆ 80    ┆ Japan  ┆ 1346.6                │
│ Datsun 510 Hatchback            ┆ 37.0 ┆ 4         ┆ 119.0        ┆ 92.0       ┆ 2434.0 ┆ 15.0         ┆ 80    ┆ Japan  ┆ 1383.6                │
│ Honda Accord                    ┆ 32.4 ┆ 4         ┆ 107.0        ┆ 72.0       ┆ 2290.0 ┆ 17.0         ┆ 80    ┆ Japan  ┆ 1416.0                │
│ …                               ┆ …    ┆ …         ┆ …            ┆ …          ┆ …      ┆ …            ┆ …     ┆ …      ┆ …                     │
│ Ford Fairmont 4                 ┆ 22.3 ┆ 4         ┆ 140.0        ┆ 88.0       ┆ 2890.0 ┆ 17.3         ┆ 79    ┆ US     ┆ 3644.2                │
│ Ford LTD Landau                 ┆ 17.6 ┆ 8         ┆ 302.0        ┆ 129.0      ┆ 3725.0 ┆ 13.4         ┆ 79    ┆ US     ┆ 3661.8                │
│ Mercury Grand Marquis           ┆ 16.5 ┆ 8         ┆ 351.0        ┆ 138.0      ┆ 3955.0 ┆ 13.2         ┆ 79    ┆ US     ┆ 3678.3                │
│ Mercury Zephyr 6                ┆ 19.8 ┆ 6         ┆ 200.0        ┆ 85.0       ┆ 2990.0 ┆ 18.2         ┆ 79    ┆ US     ┆ 3698.1                │
│ Oldsmobile Cutlass Salon Broug… ┆ 23.9 ┆ 8         ┆ 260.0        ┆ 90.0       ┆ 3420.0 ┆ 22.2         ┆ 79    ┆ US     ┆ 3722.0                │
│ Oldsmobile Omega Brougham       ┆ 26.8 ┆ 6         ┆ 173.0        ┆ 115.0      ┆ 2700.0 ┆ 12.9         ┆ 79    ┆ US     ┆ 3748.8                │
│ Plymouth Horizon                ┆ 34.2 ┆ 4         ┆ 105.0        ┆ 70.0       ┆ 2200.0 ┆ 13.2         ┆ 79    ┆ US     ┆ 3783.0                │
│ Plymouth Horizon TC3            ┆ 34.5 ┆ 4         ┆ 105.0        ┆ 70.0       ┆ 2150.0 ┆ 14.9         ┆ 79    ┆ US     ┆ 3817.5                │
│ Pontiac Lemans V6               ┆ 21.5 ┆ 6         ┆ 231.0        ┆ 115.0      ┆ 3245.0 ┆ 15.4         ┆ 79    ┆ US     ┆ 3839.0                │
│ Pontiac Phoenix                 ┆ 33.5 ┆ 4         ┆ 151.0        ┆ 90.0       ┆ 2556.0 ┆ 13.2         ┆ 79    ┆ US     ┆ 3872.5                │
│ AMC Concord                     ┆ 24.3 ┆ 4         ┆ 151.0        ┆ 90.0       ┆ 3003.0 ┆ 20.1         ┆ 80    ┆ US     ┆ 3896.8                │
│ Chevrolet Chevette              ┆ 32.1 ┆ 4         ┆ 98.0         ┆ 70.0       ┆ 2120.0 ┆ 15.5         ┆ 80    ┆ US     ┆ 3928.9                │
│ Chevrolet Citation              ┆ 28.0 ┆ 4         ┆ 151.0        ┆ 90.0       ┆ 2678.0 ┆ 16.5         ┆ 80    ┆ US     ┆ 3956.9                │
│ Dodge Aspen                     ┆ 19.1 ┆ 6         ┆ 225.0        ┆ 90.0       ┆ 3381.0 ┆ 18.7         ┆ 80    ┆ US     ┆ 3976.0                │
│ Dodge Colt                      ┆ 27.9 ┆ 4         ┆ 156.0        ┆ 105.0      ┆ 2800.0 ┆ 14.4         ┆ 80    ┆ US     ┆ 4003.9                │
│ Ford Fairmont                   ┆ 26.4 ┆ 4         ┆ 140.0        ┆ 88.0       ┆ 2870.0 ┆ 18.1         ┆ 80    ┆ US     ┆ 4030.3                │
│ Ford Mustang Cobra              ┆ 23.6 ┆ 4         ┆ 140.0        ┆ 0.0        ┆ 2905.0 ┆ 14.3         ┆ 80    ┆ US     ┆ 4053.9                │
│ Buick Century                   ┆ 22.4 ┆ 6         ┆ 231.0        ┆ 110.0      ┆ 3415.0 ┆ 15.8         ┆ 81    ┆ US     ┆ 4076.3                │
│ Buick Skylark                   ┆ 26.6 ┆ 4         ┆ 151.0        ┆ 84.0       ┆ 2635.0 ┆ 16.4         ┆ 81    ┆ US     ┆ 4102.9                │
│ Chevrolet Citation              ┆ 23.5 ┆ 6         ┆ 173.0        ┆ 110.0      ┆ 2725.0 ┆ 12.6         ┆ 81    ┆ US     ┆ 4126.4                │
│ Chrysler Lebaron Salon          ┆ 17.6 ┆ 6         ┆ 225.0        ┆ 85.0       ┆ 3465.0 ┆ 16.6         ┆ 81    ┆ US     ┆ 4144.0                │
│ Dodge Aries Wagon (sw)          ┆ 25.8 ┆ 4         ┆ 156.0        ┆ 92.0       ┆ 2620.0 ┆ 14.4         ┆ 81    ┆ US     ┆ 4169.8                │
│ Ford Escort 2H                  ┆ 29.9 ┆ 4         ┆ 98.0         ┆ 65.0       ┆ 2380.0 ┆ 20.7         ┆ 81    ┆ US     ┆ 4199.7                │
│ Ford Escort 4W                  ┆ 34.4 ┆ 4         ┆ 98.0         ┆ 65.0       ┆ 2045.0 ┆ 16.2         ┆ 81    ┆ US     ┆ 4234.1                │
│ Ford Grenada gl                 ┆ 20.2 ┆ 6         ┆ 200.0        ┆ 88.0       ┆ 3060.0 ┆ 17.1         ┆ 81    ┆ US     ┆ 4254.3                │
│ Oldsmobile Cutlass LS           ┆ 26.6 ┆ 8         ┆ 350.0        ┆ 105.0      ┆ 3725.0 ┆ 19.0         ┆ 81    ┆ US     ┆ 4280.9                │
│ Plymouth Champ                  ┆ 39.0 ┆ 4         ┆ 86.0         ┆ 64.0       ┆ 1875.0 ┆ 16.4         ┆ 81    ┆ US     ┆ 4319.9                │
│ Plymouth Horizon 4              ┆ 34.7 ┆ 4         ┆ 105.0        ┆ 63.0       ┆ 2215.0 ┆ 14.9         ┆ 81    ┆ US     ┆ 4354.6                │
│ Plymouth Reliant                ┆ 27.2 ┆ 4         ┆ 135.0        ┆ 84.0       ┆ 2490.0 ┆ 15.7         ┆ 81    ┆ US     ┆ 4381.8                │
│ Plymouth Reliant                ┆ 30.0 ┆ 4         ┆ 135.0        ┆ 84.0       ┆ 2385.0 ┆ 12.9         ┆ 81    ┆ US     ┆ 4411.8                │
│ AMC Concord DL                  ┆ 23.0 ┆ 4         ┆ 151.0        ┆ 0.0        ┆ 3035.0 ┆ 20.5         ┆ 82    ┆ US     ┆ 4434.8                │
│ Buick Century Limited           ┆ 25.0 ┆ 6         ┆ 181.0        ┆ 110.0      ┆ 2945.0 ┆ 16.4         ┆ 82    ┆ US     ┆ 4459.8                │
│ Chevrolet Camaro                ┆ 27.0 ┆ 4         ┆ 151.0        ┆ 90.0       ┆ 2950.0 ┆ 17.3         ┆ 82    ┆ US     ┆ 4486.8                │
│ Chevrolet Cavalier              ┆ 28.0 ┆ 4         ┆ 112.0        ┆ 88.0       ┆ 2605.0 ┆ 19.6         ┆ 82    ┆ US     ┆ 4514.8                │
│ Chevrolet Cavalier 2-door       ┆ 34.0 ┆ 4         ┆ 112.0        ┆ 88.0       ┆ 2395.0 ┆ 18.0         ┆ 82    ┆ US     ┆ 4548.8                │
│ Chevrolet Cavalier Wagon        ┆ 27.0 ┆ 4         ┆ 112.0        ┆ 88.0       ┆ 2640.0 ┆ 18.6         ┆ 82    ┆ US     ┆ 4575.8                │
│ Chevy S-10                      ┆ 31.0 ┆ 4         ┆ 119.0        ┆ 82.0       ┆ 2720.0 ┆ 19.4         ┆ 82    ┆ US     ┆ 4606.8                │
│ Chrysler Lebaron Medallion      ┆ 26.0 ┆ 4         ┆ 156.0        ┆ 92.0       ┆ 2585.0 ┆ 14.5         ┆ 82    ┆ US     ┆ 4632.8                │
│ Dodge Aries SE                  ┆ 29.0 ┆ 4         ┆ 135.0        ┆ 84.0       ┆ 2525.0 ┆ 16.0         ┆ 82    ┆ US     ┆ 4661.8                │
│ Dodge Charger 2.2               ┆ 36.0 ┆ 4         ┆ 135.0        ┆ 84.0       ┆ 2370.0 ┆ 13.0         ┆ 82    ┆ US     ┆ 4697.8                │
│ Dodge Rampage                   ┆ 32.0 ┆ 4         ┆ 135.0        ┆ 84.0       ┆ 2295.0 ┆ 11.6         ┆ 82    ┆ US     ┆ 4729.8                │
│ Ford Fairmont Futura            ┆ 24.0 ┆ 4         ┆ 140.0        ┆ 92.0       ┆ 2865.0 ┆ 16.4         ┆ 82    ┆ US     ┆ 4753.8                │
│ Ford Grenada l                  ┆ 22.0 ┆ 6         ┆ 232.0        ┆ 112.0      ┆ 2835.0 ┆ 14.7         ┆ 82    ┆ US     ┆ 4775.8                │
│ Ford Mustang GL                 ┆ 27.0 ┆ 4         ┆ 140.0        ┆ 86.0       ┆ 2790.0 ┆ 15.6         ┆ 82    ┆ US     ┆ 4802.8                │
│ Ford Ranger                     ┆ 28.0 ┆ 4         ┆ 120.0        ┆ 79.0       ┆ 2625.0 ┆ 18.6         ┆ 82    ┆ US     ┆ 4830.8                │
│ Mercury Lynx l                  ┆ 36.0 ┆ 4         ┆ 98.0         ┆ 70.0       ┆ 2125.0 ┆ 17.3         ┆ 82    ┆ US     ┆ 4866.8                │
│ Oldsmobile Cutlass Ciera (dies… ┆ 38.0 ┆ 6         ┆ 262.0        ┆ 85.0       ┆ 3015.0 ┆ 17.0         ┆ 82    ┆ US     ┆ 4904.8                │
│ Plymouth Horizon Miser          ┆ 38.0 ┆ 4         ┆ 105.0        ┆ 63.0       ┆ 2125.0 ┆ 14.7         ┆ 82    ┆ US     ┆ 4942.8                │
│ Pontiac J2000 SE Hatchback      ┆ 31.0 ┆ 4         ┆ 112.0        ┆ 85.0       ┆ 2575.0 ┆ 16.2         ┆ 82    ┆ US     ┆ 4973.8                │
│ Pontiac Phoenix                 ┆ 27.0 ┆ 4         ┆ 151.0        ┆ 90.0       ┆ 2735.0 ┆ 18.0         ┆ 82    ┆ US     ┆ 5000.8                │
└─────────────────────────────────┴──────┴───────────┴──────────────┴────────────┴────────┴──────────────┴───────┴────────┴───────────────────────┘